### ISSUE TITLE
update StepupFix-1.10.2-1.0.0.2 crashes

### ISSUE THREAD

**Issue by K4N0** [Aroma1997/StepupFix#1]
It actuallly does not even crash. it just won't load and closes quickly.
StepupFix-1.10.2-1.0.0.2

**Comment by Aroma1997** [comment]
Make sure, you're running the latest version of AromaCore alongside with it.
If the bug persists, please send me your log file.

**Comment by K4N0** [comment]
Thank You, I did need to update AromaCore. I forgot it used that too.
